Entity/Coupons.php
<?php

namespace CMS\CouponsBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * Coupons
 */
class Coupons
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $title;

    /**
     * @var float
     */
    private $price;

    /**
     * @var ArrayCollection Photos
     */
    private $photos;

    /**
     * @var boolean
     */
    private $is_published;

    /**
     * @var boolean
     */
    private $is_deleted;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    public function __construct()
    {
        $this->photos = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param \string $title
     *
     * @return Coupons
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return $this
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return \Doctrine\Common\Collections\ArrayCollection
     */
    public function getPhotos()
    {
        return $this->photos;
    }

    /**
     * @param \Doctrine\Common\Collections\ArrayCollection $photos
     * @return $this
     */
    public function setPhotos($photos)
    {
        $this->photos = $photos;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->is_published;
    }

    /**
     * @param boolean $is_published
     * @return $this
     */
    public function setIsPublished($is_published)
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * @param boolean $is_deleted
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * @param \DateTime $date_create
     * @return $this
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }

    /**
     * @param \DateTime $date_update
     * @return $this
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * @return int
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * @param int $create_by
     * @return $this
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * @return int
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * @param int $update_by
     * @return $this
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;
        return $this;
    }
}

Entity/CouponsRepository.php
<?php

namespace CMS\CouponsBundle\Entity;

use CMS\CoreBundle\AbstractCoreRepository;

/**
 * CouponsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouponsRepository extends AbstractCoreRepository
{
    /**
     * Return name repository for crud
     *
     * @return string
     */
    public function getRepositoryName()
    {
        return 'CouponsBundle:Coupons';
    }

}

Form/CouponsType.php
<?php

namespace CMS\CouponsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CouponsType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'cms_localization_text_type')
            ->add('price')
            ->add('is_published')
            ->add('is_deleted')
            ->add('photos', 'cms_gallery_images_type');
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\CouponsBundle\Entity\Coupons'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'cms_couponsbundle_coupons';
    }
}

Controller/CouponsController.php
<?php

namespace CMS\CouponsBundle\Controller;

use CMS\CouponsBundle\Entity\Coupons;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class CouponsController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function listAction()
    {
        return $this->render('CouponsBundle:Coupons:list.html.twig', array(
            'coupons' => $this->get('cms.coupons.service')->findAll()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.coupons.service');

        $form = $service->generateForm($service->findOneById($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->create($form->getData());

                return $this->redirect($this->generateUrl('cms_coupons_list'));
            }
        }

        return $this->render('CouponsBundle:Coupons:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function createAction(Request $request)
    {
        $service = $this->get('cms.coupons.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $service->create($form->getData());

                return $this->redirect($this->generateUrl('cms_coupons_list'));
            }
        }

        return $this->render('CouponsBundle:Coupons:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function deleteAction($id)
    {
        $service = $this->get('cms.coupons.service');

        $service->delete($id);

        return $this->redirect($this->generateUrl('cms_coupons_list'));
    }
}

Tests/Controller/DefaultControllerTest.php
<?php

namespace CMS\CouponsBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}

Resources/views/Coupons/edit.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts '@file_uploader'
    'bundles/localization/js/localization_form.js'
    'bundles/restaurants/js/fileuploader.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets
    '@fileupload_css' %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed "CouponsBundle::main.html.twig" %}
        {% block main %}
            <div class="row">
                {% form_theme form 'CouponsBundle::fields.html.twig' %}
                <div class="col-md-12">
                    {{ show_locale_tabs() }}
                    <br/>

                    <form method="post" {{ form_enctype(form) }} class="form-horizontal">
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title,{
                                    'label': 'Title'|trans({},'labels'),
                                }) }}
                                {{ form_row(form.price,{
                                    'label': 'Price'|trans({},'labels'),
                                }) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Coupons/list.html.twig
{% extends 'DashboardBundle:Layout:base.html.twig' %}

{% block body %}
    {% embed 'CouponsBundle::main.html.twig' %}
        {% block panelButtons %}
            <a href="{{ url('cms_coupons_create') }}"
               class="glyphicon glyphicon-plus btn btn-success btn-xs">{{ 'Add'|trans }}</a>
        {% endblock %}

        {% block main %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th><input type="checkbox" data-action="selectAll"/></th>
                    <th>ID</th>
                    <th>{{ 'Title'|trans }}</th>
                    <th>{{ 'Status'|trans }}</th>
                    <th>{{ 'Create by'|trans }}</th>
                    <th>{{ 'Date'|trans }}</th>
                    <th></th>
                    <th></th>
                    </thead>
                    <tbody>
                    {% for coupon in coupons %}
                        <tr>
                            <td><input type="checkbox" value="{{ coupon.id }}" name="mark[]"/></td>
                            <td>{{ coupon.id }}</td>
                            <td>
                                <a href="{{ url('cms_coupons_edit', {id: coupon.id}) }}">
                                    {{ coupon.title|locale }}
                                </a>
                            </td>
                            <td></td>
                            <td>{{ coupon.createBy }}</td>
                            <td>{{ coupon.dateCreate|date('d.m.Y') }}</td>
                            <td><a href='{{ url('cms_coupons_edit', {id: coupon.id}) }}'><span
                                            class="glyphicon lead text-primary glyphicon-pencil"></span></a></td>
                            <td><a href='{{ url('cms_coupons_delete', {id: coupon.id}) }}'><span
                                            class="glyphicon lead text-danger glyphicon-remove-circle"></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/fields.html.twig
{% block form_row %}
    <div class="form-group clearfix">
        {{ form_label(form) }}
        <div class="col-md-8">
            {{ form_widget(form) }}
            {{ form_errors(form) }}
        </div>
    </div>
{% endblock form_row %}

{% block widget_attributes %}
    {% spaceless %}
        {% set attr = attr|merge({'class': attr.class|default('') ~ ' form-control'}) %}
        id="{{ id }}" name="{{ full_name }}"{% if read_only %} readonly="readonly"{% endif %}{% if disabled %} disabled="disabled"{% endif %}{% if required %} required="required"{% endif %}{% if max_length %} maxlength="{{ max_length }}"{% endif %}{% if pattern %} pattern="{{ pattern }}"{% endif %}
        {% for attrname, attrvalue in attr %}{% if attrname in ['placeholder', 'title'] %}{{ attrname }}="{{ attrvalue|trans({}, translation_domain) }}" {% else %}{{ attrname }}="{{ attrvalue }}" {% endif %}{% endfor %}
    {% endspaceless %}
{% endblock widget_attributes %}

{% block form_label %}
    {% spaceless %}
        {% if label is not sameas(false) %}
            {% if not compound %}
    {% set label_attr = label_attr|merge({'for': id}) %}
{% endif %}
            {% if required %}
    {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
{% endif %}
            {% if label is empty %}
    {% set label = name|humanize %}
{% endif %}
            {% if label is iterable %}
    {% set label = label|locale %}
{% endif %}
            {% set label_attr = label_attr|merge({'class': label_attr.class|default('') ~ ' col-sm-2 control-label'}) %}
            <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, translation_domain) }}:</label>
        {% endif %}
    {% endspaceless %}
{% endblock form_label %}
    
{% block choice_widget_expanded %}
    {% spaceless %}
        <div {{ block('widget_container_attributes') }}>
            {% for child in form %}
                {{ form_label(child) }}{{ form_widget(child) }}
            {% endfor %}
        </div>
    {% endspaceless %}
{% endblock choice_widget_expanded %}

{% block cms_localization_text_type_widget %}
    {% for child in form %}
        {% if child.vars.name|lower != app.request.locale|lower %}
            {{ form_widget(child, {'attr': {'style':'display:none' }}) }}
        {% else %}
            {{ form_widget(child) }}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block cms_localization_textarea_type_widget %}
    {% for child in form %}
        {% if child.vars.name|lower != app.request.locale|lower %}
            {{ form_widget(child, {'attr': {'style':'display:none' }}) }}
        {% else %}
            {{ form_widget(child) }}
        {% endif %}
    {% endfor %}
{% endblock %}

{% block cms_localization_entity_type_widget %}
    {% spaceless %}
        {% if expanded %}
            <div {{ block('widget_container_attributes') }}>
                {% for child in form %}
                    <div class="checkbox">
                        <label>
                            {{ form_widget(child) }}
                        </label>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            {{ form_widget(form) }}
        {% endif %}
    {% endspaceless %}
{% endblock cms_localization_entity_type_widget %}

{%- block choice_widget_options -%}
    {% for group_label, choice in options %}
        {% set label = choice.label %}

        {% if label is iterable %}
            {% set label = label|locale %}
        {% endif %}

        {%- if choice is iterable -%}
            <optgroup label="{{ group_label|trans({}, translation_domain) }}">
                {% set options = choice %}
                {{- block('choice_widget_options') -}}
            </optgroup>
        {%- else -%}
            <option value="{{ choice.value }}"{% if choice is selectedchoice(value) %} selected="selected"{% endif %}>{{ label|trans({}, translation_domain) }}</option>
        {%- endif -%}
    {% endfor %}
{%- endblock choice_widget_options -%}

{% block checkbox_widget %}
    {% spaceless %}
        {% if label is iterable %}
            {% set label = label|locale %}
        {% endif %}
        <input type="checkbox"
               name="{{ full_name }}" {% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
        {{ label }}
    {% endspaceless %}
{% endblock checkbox_widget %}

{% block form_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul class="list-unstyled">
                {% for error in errors %}
                    <li class="text-danger">{{ error.message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock form_errors %}

{% block cms_gallery_images_type_widget %}
    {% spaceless %}
        <div class="row">
            {{ form_errors(form) }}
            <div id="gallery_images" data-prototype="{{ form_widget(form.vars.prototype)|e }}">
                {% for child in form.children %}
                    {{ form_widget(child) }}
                {% endfor %}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <span class="btn btn-primary fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>{{ 'labels.add_files'|trans({}, 'gallery') }}</span>
                    <input type="file" id="imageupload" name="file"
                           data-url="{{ path('cms_gallery_upload_image') }}">
                </span>
            </div>
        </div>
    {% endspaceless %}
{% endblock cms_gallery_images_type_widget %}

{% block cms_gallery_image_type_widget %}
    {% spaceless %}
        <div class="col-sm-6 col-md-6 gallery_image">
            <div id="{{ form.vars.id }}" class="thumbnail">
                <div class="control-panel">
                    <i class="icon delete" title="{{ 'title.delete_image'|trans({}, 'gallery') }}"></i>
                    <i class="icon edit" title="{{ 'title.edit_image'|trans({}, 'gallery') }}"></i>
                </div>
                <img src="/{{ image_url(form.path.vars.value, 256, 256) }}">
                <div class="caption">
                    {{ form_widget(form.descriptions) }}
                    {{ form_widget(form.path) }}
                </div>
            </div>
        </div>
    {% endspaceless %}
{% endblock cms_gallery_image_type_widget %}

{% block cms_hotels_seasons_type_widget %}
    {% spaceless %}
        <div class="row">
            {{ form_errors(form) }}
            <div id="seasons" class="col-md-12 col-sm-12" data-prototype="{{ form_widget(form.vars.prototype)|e }}">
                {% for child in form.children %}
                    {{ form_widget(child) }}
                {% endfor %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-12 col-md-12">
                <span class="btn btn-primary" id="add_season">
                    <i class="glyphicon glyphicon-plus"></i>
                    {{ 'Add'|trans({}, translation_domain) }}
                </span>
            </div>
        </div>
    {% endspaceless %}
{% endblock cms_hotels_seasons_type_widget %}

{% block cms_hotels_season_type_widget %}
    {% spaceless %}
        <div class="panel panel-default season">
            <div class="panel-heading clearfix">
                <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-sm-6 col-md-6">
                        <div class="input-group">
                            {{ form_widget(form.date_start) }}
                            <div class="input-group-addon">
                                <i class="glyphicon glyphicon-calendar"></i>
                            </div>
                            {{ form_errors(form.date_start) }}
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-6">
                        <div class="input-group">
                            {{ form_widget(form.date_end) }}
                            <div class="input-group-addon">
                                <i class="glyphicon glyphicon-calendar"></i>
                            </div>
                            {{ form_errors(form.date_end) }}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        {{ form_widget(form.price) }}
                        {{ form_errors(form.price) }}
                    </div>
                </div>
            </div>
        </div>
    {% endspaceless %}
{% endblock cms_hotels_season_type_widget %}

Resources/views/main.html.twig
<div class="col-md-12">
    <div class="row">
        {% include 'RestaurantsBundle::panel.html.twig' with { panelButtons: block('panelButtons')} %}
    </div>
    <div class="row">
        {% block main %}{% endblock %}
    </div>
</div>

Resources/views/panel.html.twig
<div class="panel panel-default">
    <div class="panel-body controllPanel">
        <div class="col-md-7 title"><strong>{{ breadcrumb() }}</strong></div>
        <div class="col-md-5 buttons text-right">
            {{ panelButtons|raw }}
        </div>
    </div>
</div>